apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp.settingserver.com
  namespace: myapp 
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: myapp-service
          servicePort: 80

